<template>
	<div id="InputFieldCard-wrapper" class="row card">
		<div class="input-field col s6">
			<input id="last_name" type="text" class="validate" v-model="playerName" />
			<label for="last_name" id="nameLabel">Name</label>
		</div>

		<div class="input-field col s6 heading3">
			<select v-model="playerCountryCode">
				<option value="" disabled selected>Select Your Country</option>
				<option
					value="AD"
					data-icon="https://www.countryflags.io/AD/flat/64.png"
					>Andorra</option
				>
				<option
					value="AE"
					data-icon="https://www.countryflags.io/AE/flat/64.png"
					>UAE</option
				>
				<option
					value="AL"
					data-icon="https://www.countryflags.io/AL/flat/64.png"
					>Albania</option
				>
				<option
					value="AM"
					data-icon="https://www.countryflags.io/AM/flat/64.png"
					>Armenia</option
				>
				<option
					value="AR"
					data-icon="https://www.countryflags.io/AR/flat/64.png"
					>Argentina</option
				>
				<option
					value="AT"
					data-icon="https://www.countryflags.io/AT/flat/64.png"
					>Austria</option
				>
				<option
					value="AU"
					data-icon="https://www.countryflags.io/AU/flat/64.png"
					>Australia</option
				>
				<option
					value="AZ"
					data-icon="https://www.countryflags.io/AZ/flat/64.png"
					>Azerbaijan</option
				>
				<option
					value="BD"
					data-icon="https://www.countryflags.io/BD/flat/64.png"
					>Bangladesh</option
				>
				<option
					value="BE"
					data-icon="https://www.countryflags.io/BE/flat/64.png"
					>Belgium</option
				>
				<option
					value="BG"
					data-icon="https://www.countryflags.io/BG/flat/64.png"
					>Bulgaria</option
				>
				<option
					value="BH"
					data-icon="https://www.countryflags.io/BH/flat/64.png"
					>Baharain</option
				>
				<option
					value="BI"
					data-icon="https://www.countryflags.io/BI/flat/64.png"
					>Burundi</option
				>
				<option
					value="BN"
					data-icon="https://www.countryflags.io/BN/flat/64.png"
					>Brunei</option
				>
				<option
					value="BO"
					data-icon="https://www.countryflags.io/BO/flat/64.png"
					>Bolivia</option
				>
				<option
					value="BR"
					data-icon="https://www.countryflags.io/BR/flat/64.png"
					>Brazil</option
				>
				<option
					value="BS"
					data-icon="https://www.countryflags.io/BS/flat/64.png"
					>Bahamas</option
				>
				<option
					value="BT"
					data-icon="https://www.countryflags.io/BT/flat/64.png"
					>Bhutan</option
				>
				<option
					value="BY"
					data-icon="https://www.countryflags.io/BY/flat/64.png"
					>Belarus</option
				>
				<option
					value="BZ"
					data-icon="https://www.countryflags.io/BZ/flat/64.png"
					>Belize</option
				>
				<option
					value="CA"
					data-icon="https://www.countryflags.io/CA/flat/64.png"
					>Canada</option
				>
				<option
					value="CH"
					data-icon="https://www.countryflags.io/CH/flat/64.png"
					>Switzerland</option
				>
				<option
					value="CL"
					data-icon="https://www.countryflags.io/CL/flat/64.png"
					>Chile</option
				>
				<option
					value="CM"
					data-icon="https://www.countryflags.io/CM/flat/64.png"
					>Cameroon</option
				>
				<option
					value="CN"
					data-icon="https://www.countryflags.io/CN/flat/64.png"
					>China</option
				>
				<option
					value="CO"
					data-icon="https://www.countryflags.io/CO/flat/64.png"
					>Colombia</option
				>
				<option
					value="CU"
					data-icon="https://www.countryflags.io/CU/flat/64.png"
					>Cuba</option
				>
				<option
					value="CY"
					data-icon="https://www.countryflags.io/CY/flat/64.png"
					>Cyprus</option
				>
				<option
					value="CZ"
					data-icon="https://www.countryflags.io/CZ/flat/64.png"
					>Czechia</option
				>
				<option
					value="DE"
					data-icon="https://www.countryflags.io/DE/flat/64.png"
					>Germany</option
				>
				<option
					value="DK"
					data-icon="https://www.countryflags.io/DK/flat/64.png"
					>Denmark</option
				>
				<option
					value="EE"
					data-icon="https://www.countryflags.io/EE/flat/64.png"
					>Estonia</option
				>
				<option
					value="EG"
					data-icon="https://www.countryflags.io/EG/flat/64.png"
					>Egypt</option
				>
				<option
					value="ES"
					data-icon="https://www.countryflags.io/ES/flat/64.png"
					>Spain</option
				>
				<option
					value="ET"
					data-icon="https://www.countryflags.io/ET/flat/64.png"
					>Ethiopia</option
				>
				<option
					value="FI"
					data-icon="https://www.countryflags.io/FI/flat/64.png"
					>Finland</option
				>
				<option
					value="FR"
					data-icon="https://www.countryflags.io/FR/flat/64.png"
					>France</option
				>
				<option
					value="GB"
					data-icon="https://www.countryflags.io/GB/flat/64.png"
					>United Kingdom</option
				>
				<option
					value="GE"
					data-icon="https://www.countryflags.io/GE/flat/64.png"
					>Georgia</option
				>
				<option
					value="GL"
					data-icon="https://www.countryflags.io/GL/flat/64.png"
					>Greenland</option
				>
				<option
					value="GR"
					data-icon="https://www.countryflags.io/GR/flat/64.png"
					>Greece</option
				>
				<option
					value="GT"
					data-icon="https://www.countryflags.io/GT/flat/64.png"
					>Guatemala</option
				>
				<option
					value="HK"
					data-icon="https://www.countryflags.io/HK/flat/64.png"
					>Hong Kong</option
				>
				<option
					value="HN"
					data-icon="https://www.countryflags.io/HN/flat/64.png"
					>Honduras</option
				>
				<option
					value="HR"
					data-icon="https://www.countryflags.io/HR/flat/64.png"
					>Croatia</option
				>
				<option
					value="HT"
					data-icon="https://www.countryflags.io/HT/flat/64.png"
					>Haiti</option
				>
				<option
					value="HU"
					data-icon="https://www.countryflags.io/HU/flat/64.png"
					>Hungary</option
				>
				<option
					value="ID"
					data-icon="https://www.countryflags.io/ID/flat/64.png"
					>Indonesia</option
				>
				<option
					value="IE"
					data-icon="https://www.countryflags.io/IE/flat/64.png"
					>Ireland</option
				>
				<option
					value="IL"
					data-icon="https://www.countryflags.io/IL/flat/64.png"
					>Israel</option
				>
				<option
					value="IN"
					data-icon="https://www.countryflags.io/IN/flat/64.png"
					>India</option
				>
				<option
					value="IQ"
					data-icon="https://www.countryflags.io/IQ/flat/64.png"
					>Iraq</option
				>
				<option
					value="IR"
					data-icon="https://www.countryflags.io/IR/flat/64.png"
					>Iran</option
				>
				<option
					value="IS"
					data-icon="https://www.countryflags.io/IS/flat/64.png"
					>Iceland</option
				>
				<option
					value="IT"
					data-icon="https://www.countryflags.io/IT/flat/64.png"
					>Italy</option
				>
				<option
					value="JM"
					data-icon="https://www.countryflags.io/JM/flat/64.png"
					>Jamaica</option
				>
				<option
					value="JO"
					data-icon="https://www.countryflags.io/JO/flat/64.png"
					>Jordan</option
				>
				<option
					value="JP"
					data-icon="https://www.countryflags.io/JP/flat/64.png"
					>Japan</option
				>
				<option
					value="KR"
					data-icon="https://www.countryflags.io/KR/flat/64.png"
					>South Korea</option
				>
				<option
					value="LI"
					data-icon="https://www.countryflags.io/LI/flat/64.png"
					>Liechtenstein</option
				>
				<option
					value="LK"
					data-icon="https://www.countryflags.io/LK/flat/64.png"
					>Sri Lanka</option
				>
				<option
					value="LT"
					data-icon="https://www.countryflags.io/LT/flat/64.png"
					>Lithuania</option
				>
				<option
					value="LU"
					data-icon="https://www.countryflags.io/LU/flat/64.png"
					>Luxembourg</option
				>
				<option
					value="LV"
					data-icon="https://www.countryflags.io/LV/flat/64.png"
					>Latvia</option
				>
				<option
					value="MA"
					data-icon="https://www.countryflags.io/MA/flat/64.png"
					>Morocco</option
				>
				<option
					value="MC"
					data-icon="https://www.countryflags.io/MC/flat/64.png"
					>Monaco</option
				>
				<option
					value="MD"
					data-icon="https://www.countryflags.io/MD/flat/64.png"
					>Moldava</option
				>
				<option
					value="ME"
					data-icon="https://www.countryflags.io/ME/flat/64.png"
					>Montenegro</option
				>
				<option
					value="MG"
					data-icon="https://www.countryflags.io/MG/flat/64.png"
					>Madagascar</option
				>
				<option
					value="MN"
					data-icon="https://www.countryflags.io/MN/flat/64.png"
					>Mongolia</option
				>
				<option
					value="MT"
					data-icon="https://www.countryflags.io/MT/flat/64.png"
					>Malta</option
				>
				<option
					value="MX"
					data-icon="https://www.countryflags.io/MX/flat/64.png"
					>Mexico</option
				>
				<option
					value="MY"
					data-icon="https://www.countryflags.io/MY/flat/64.png"
					>Malaysia</option
				>
				<option
					value="NE"
					data-icon="https://www.countryflags.io/NE/flat/64.png"
					>Niger</option
				>
				<option
					value="NG"
					data-icon="https://www.countryflags.io/NG/flat/64.png"
					>Nigeria</option
				>
				<option
					value="NI"
					data-icon="https://www.countryflags.io/NI/flat/64.png"
					>Nicaragua</option
				>
				<option
					value="NL"
					data-icon="https://www.countryflags.io/NL/flat/64.png"
					>Netherlands</option
				>
				<option
					value="NO"
					data-icon="https://www.countryflags.io/NO/flat/64.png"
					>Norway</option
				>
				<option
					value="NP"
					data-icon="https://www.countryflags.io/NP/flat/64.png"
					>Nepal</option
				>
				<option
					value="NR"
					data-icon="https://www.countryflags.io/NR/flat/64.png"
					>Nauru</option
				>
				<option
					value="NZ"
					data-icon="https://www.countryflags.io/NZ/flat/64.png"
					>New Zealand</option
				>
				<option
					value="PA"
					data-icon="https://www.countryflags.io/PA/flat/64.png"
					>Panama</option
				>
				<option
					value="PE"
					data-icon="https://www.countryflags.io/PE/flat/64.png"
					>Peru</option
				>
				<option
					value="PF"
					data-icon="https://www.countryflags.io/PF/flat/64.png"
					>French Polynesia</option
				>
				<option
					value="PH"
					data-icon="https://www.countryflags.io/PH/flat/64.png"
					>Philippines</option
				>
				<option
					value="PK"
					data-icon="https://www.countryflags.io/PK/flat/64.png"
					>Pakistan</option
				>
				<option
					value="PL"
					data-icon="https://www.countryflags.io/PL/flat/64.png"
					>Poland</option
				>
				<option
					value="PR"
					data-icon="https://www.countryflags.io/PR/flat/64.png"
					>Puerto Rico</option
				>
				<option
					value="PT"
					data-icon="https://www.countryflags.io/PT/flat/64.png"
					>Portugal</option
				>
				<option
					value="PY"
					data-icon="https://www.countryflags.io/PY/flat/64.png"
					>Paraguay</option
				>
				<option
					value="QA"
					data-icon="https://www.countryflags.io/QA/flat/64.png"
					>Qatar</option
				>
				<option
					value="RO"
					data-icon="https://www.countryflags.io/RO/flat/64.png"
					>Romania</option
				>
				<option
					value="RS"
					data-icon="https://www.countryflags.io/RS/flat/64.png"
					>Serbia</option
				>
				<option
					value="RU"
					data-icon="https://www.countryflags.io/RU/flat/64.png"
					>Russia</option
				>
				<option
					value="SA"
					data-icon="https://www.countryflags.io/SA/flat/64.png"
					>Saudi Arabia</option
				>
				<option
					value="SD"
					data-icon="https://www.countryflags.io/SD/flat/64.png"
					>Sudan</option
				>
				<option
					value="SE"
					data-icon="https://www.countryflags.io/SE/flat/64.png"
					>Sweden</option
				>
				<option
					value="SG"
					data-icon="https://www.countryflags.io/SG/flat/64.png"
					>Singapore</option
				>
				<option
					value="SL"
					data-icon="https://www.countryflags.io/SL/flat/64.png"
					>Slovenia</option
				>
				<option
					value="SK"
					data-icon="https://www.countryflags.io/SK/flat/64.png"
					>Slovakia</option
				>
				<option
					value="SV"
					data-icon="https://www.countryflags.io/SV/flat/64.png"
					>El Salvador</option
				>
				<option
					value="SY"
					data-icon="https://www.countryflags.io/SY/flat/64.png"
					>Syria</option
				>
				<option
					value="TH"
					data-icon="https://www.countryflags.io/TH/flat/64.png"
					>Thailand</option
				>
				<option
					value="TM"
					data-icon="https://www.countryflags.io/TM/flat/64.png"
					>Turkmenistan</option
				>
				<option
					value="TR"
					data-icon="https://www.countryflags.io/TR/flat/64.png"
					>Turkey</option
				>
				<option
					value="TW"
					data-icon="https://www.countryflags.io/TW/flat/64.png"
					>Taiwan</option
				>
				<option
					value="UA"
					data-icon="https://www.countryflags.io/UA/flat/64.png"
					>Ukraine</option
				>
				<option
					value="US"
					data-icon="https://www.countryflags.io/US/flat/64.png"
					>United States</option
				>
				<option
					value="VE"
					data-icon="https://www.countryflags.io/VE/flat/64.png"
					>Venezuela</option
				>
				<option
					value="VN"
					data-icon="https://www.countryflags.io/KR/flat/64.png"
					>Vietnam</option
				>
				<option
					value="YE"
					data-icon="https://www.countryflags.io/YE/flat/64.png"
					>Yemen</option
				>
				<option
					value="ZA"
					data-icon="https://www.countryflags.io/ZA/flat/64.png"
					>South Africa</option
				>
				<option
					value="ZW"
					data-icon="https://www.countryflags.io/ZW/flat/64.png"
					>Zimbabwe</option
				>
			</select>
			<label for="last_name">Country</label>
		</div>
	</div>
</template>

<script>
import M from "materialize-css";

export default {
	name: "InputFieldCard",
	mounted() {
		let elems = document.querySelectorAll("select");
		let instances = M.FormSelect.init(elems, {});

		instances.forEach((instance) => {
			instance.input.style.fontFamily = '"Titillium Web", sans-serif';
		});
	},
	data() {
		return {
			playerName: null,
			playerCountryCode: null,
		};
	},
	watch: {
		playerName() {
			this.$emit("playerName:changed", this.playerName);
		},
		playerCountryCode() {
			this.$emit("playerCountryCode:changed", this.playerCountryCode);
		},
	},
};
</script>

<style lang="scss" scoped>
@import "../assets/scss/_text.scss";
@import "../assets/scss/_settings.scss";

#nameLabel {
	font-family: "Titillium Web", sans-serif;
}
</style>
